name: Compile Examples

# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    paths:
      - ".github/workflows/compile-examples.ya?ml"
      - "library.properties"
      - "examples/**"
      - "src/**"
  pull_request:
    paths:
      - ".github/workflows/compile-examples.ya?ml"
      - "library.properties"
      - "examples/**"
      - "src/**"
  schedule:
    # Run every Tuesday at 8 AM UTC to catch breakage caused by changes to external resources (libraries, platforms).
    - cron: "0 8 * * TUE"
  workflow_dispatch:
  repository_dispatch:

env:
  UNIVERSAL_SKETCH_PATHS: |
        - examples/Battery
        - examples/Charger
        - examples/Standby_WakeFromPin
  SKETCHES_REPORTS_PATH: sketches-reports
  SKETCHES_REPORTS_ARTIFACT_NAME: sketches-reports

jobs:
  build:
    name: ${{ matrix.board.fqbn }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    strategy:
      fail-fast: false

      matrix:
        board:
          - fqbn: arduino:renesas_portenta:portenta_c33
            platforms: |
              - name: arduino:renesas_portenta
            artifact-name-suffix: arduino-renesas_portenta-portenta_c33
            additional-sketch-paths: examples/ChargStandby_WakeFromRTC_C33er
          - fqbn: arduino:mbed_portenta:envie_m7
            platforms: |
              - name: arduino:mbed_portenta
            artifact-name-suffix: arduino-mbed_portenta-envie_m7
            additional-sketch-paths: examples/Standby_WakeFromRTC_H7


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile examples
        uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{ matrix.board.fqbn }}
          platforms: ${{ matrix.board.platforms }}
          libraries: |
            # Install the library from the local path.
            - source-path: ./
            # - name: Arduino_PF1550
            - source-url: https://github.com/arduino-libraries/Arduino_PF1550.git
            - source-url: https://github.com/arduino-libraries/Arduino_LowPowerPortentaC33.git
          sketch-paths: |
            ${{ env.UNIVERSAL_SKETCH_PATHS }}
            ${{ matrix.board.additional-sketch-paths }}
          enable-deltas-report: true
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}

      - name: Save sketches report as workflow artifact
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          path: ${{ env.SKETCHES_REPORTS_PATH }}
          name: ${{ env.SKETCHES_REPORTS_ARTIFACT_NAME }}

  report-size-deltas:
    needs: build
    # Run even if some compilations failed.
    if: always() && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Download sketches reports artifact
        id: download-artifact
        continue-on-error: true # If compilation failed for all boards then there are no artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.SKETCHES_REPORTS_ARTIFACT_NAME }}
          path: ${{ env.SKETCHES_REPORTS_PATH }}

      - name: Comment size deltas report to PR
        uses: arduino/report-size-deltas@v1
        # If actions/download-artifact failed, there are no artifacts to report from.
        if: steps.download-artifact.outcome == 'success'
        with:
          sketches-reports-source: ${{ env.SKETCHES_REPORTS_PATH }}